DROP TABLE IF EXISTS hotel cascade;
DROP TABLE IF EXISTS manager cascade;
DROP TABLE IF EXISTS traveller cascade;
DROP TABLE IF EXISTS vehicle cascade;
DROP TABLE IF EXISTS tour cascade;
DROP TABLE IF EXISTS route cascade;
DROP TABLE IF EXISTS ticket cascade;
CREATE TABLE hotel
(
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)  NOT NULL,
    type    VARCHAR(50)  NOT NULL,
    address VARCHAR(250) NOT NULL
);
CREATE TABLE manager(
    id        INT PRIMARY KEY NOT NULL,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL
);
CREATE TABLE traveller
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15),
    email     VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE vehicle(
   id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   type SMALLINT NOT NULL
);

CREATE TABLE route
(
   id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   places VARCHAR(500) NOT NULL,
   hotel_id INT[] NOT NULL
);
CREATE TABLE tour(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL,
    numberOfDays INT NOT NULL,
    price INT DEFAULT 0,
	vehicle_id INT NOT NULL,
	route_id INT NOT NULL,
    FOREIGN KEY (route_id) REFERENCES route (id)
);
CREATE TABLE ticket
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    traveller_id INT NOT NULL,
    tour_id    INT NOT NULL,
    seats INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    FOREIGN KEY (traveller_id) REFERENCES traveller (id),
    FOREIGN KEY (tour_id) REFERENCES tour (id)
);

INSERT INTO hotel(name,type, address)
VALUES  ('Büyük Abant', 'Hotel','Mudurnu/Bolu'),
        ('Dedeman', 'Hotel','Merkez/Zonguldak'),
        ('Fimar Life', 'Resort','Çiviköy/Amasya'),
        ('Grand Atakum', 'Hotel', 'Atakum/Samsun'),
        ('Mercure', 'Hotel','Ilıcaköy/Trabzon // İkizdere/Trabzon'),
        ('Ridos', 'Thermal', 'İkizdere/Rize');
INSERT INTO route(places,hotel_id)
VALUES ('Bolu/Zonguldak/Amasya/Samsun/Trabzon/Rize','{1,2,3,4,5,6}'),
('Bolu/Amasya/Samsun/Trabzon','{1,3,4,5,6}');

INSERT INTO traveller(firstname, lastname, gender, age, phone, email)
VALUES ('Rümeysa', 'Türker', 'female', 26, '905554443322', 'rumeysatur@gmail.com'),
       ('Hasan', 'Uçar', 'male', 18, '905556527890', 'hasan@gmail.com'),
       ('Kayra', 'Sever', 'female', 37, '905554443322', 'kayra@gmail.com'),
       ('Cihan', 'Tok', 'male', 25, '905554443324', 'cihan@gmail.com'),
       ('Sabiha', 'Kara', 'female', 42,'905554443324', 'sabiha@gmail.com'),
       ('Kemal', 'Güneş', 'male', 56, '905554443322', 'kemal@hotmail.com'),
       ('Servet', 'Şanlı', 'male', 30, '905554443322', 'servet@hotmail.com');
INSERT INTO tour(name,numberofdays,price,vehicle_id,route_id)
VALUES('Karadeniz Turu',7,3000,2,1),
      ('Karadeniz Turu',5,2400,1,2);

INSERT INTO ticket(traveller_id, tour_id,seats,start_date,end_date)
VALUES (1, 1,2,'2022-03-04','2022-03-11'),
       (3,2,3,'2022-04-10','2022-04-15');

